[general]
shuffle_caption = false
caption_extension = ".txt"
keep_tokens = 1

[[datasets]]
resolution = 512
batch_size = 1
keep_tokens = 1

  [[datasets.subsets]]
  image_dir = "/workspace/music-video-generator/training_workspace/train_data_stable"
  class_tokens = "anddrrew"
  num_repeats = 10
